.travis.yml
tests/testthat/test-brms.R

Improve testing

---

vignettes/bayes_factors.Rmd

Enhance bf

---

DESCRIPTION

I'm adding my ORCID to the DESCRIPTION file.

add an ORCID

---

R/describe_posterior.R
man/describe_posterior.Rd

exact links

---

vignettes/credible_interval.Rmd
vignettes/guidelines.Rmd
vignettes/region_of_practical_equivalence.Rmd

Thanks so much for providing detailed documentation on how to apply the tests in bayestestR.
I have found a few minor improvements to the text while reading them.

Minor tweaks to vignettes

---

R/bayesfactor_parameters.R
R/ci.R
R/describe_posterior.R
R/si.R
R/utils_bayesfactor.R
man/bayesfactor_parameters.Rd
man/ci.Rd
man/describe_posterior.Rd
man/si.Rd
tests/testthat/test-describe_posterior.R
tests/testthat/test-emmGrid.R
tests/testthat/test-rope.R

@DominiqueMakowski @strengejacke please take a (quick) look at the implementation (:

SI methods to `ci()` and `describe_posterior()`

---

DESCRIPTION
R/bayesfactor_inclusion.R
R/bayesfactor_parameters.R
bayestestR.Rproj
man/bayesfactor_inclusion.Rd
man/bayesfactor_parameters.Rd

related to https://github.com/easystats/bayestestR/issues/282

Fix CRAN checks

---

NEWS.md
R/weighted_posteriors.R
man/distribution.Rd
man/weighted_posteriors.Rd

fixed #286

---

R/utils_bayesfactor.R
R/weighted_posteriors.R
tests/testthat/test-weighted_posteriors.R

close #299

---

DESCRIPTION

bump version (0.0.6) CRAN

---

man/si.Rd
vignettes/credible_interval.Rmd

fixed typo

---

R/eti.R
R/hdi.R
R/print.ci.R
R/print.describe_posterior.R
R/utils_hdi_ci.R

See https://github.com/easystats/bayestestR/issues/365

CI as fraction #365

---

_pkgdown.yml
vignettes/bayes_factors.Rmd
vignettes/bayestestR.Rmd
vignettes/credible_interval.Rmd
vignettes/example1.Rmd
vignettes/example2.Rmd
vignettes/example3.Rmd
vignettes/guidelines.Rmd
vignettes/indicesEstimationComparison.Rmd
vignettes/indicesExistenceComparison.Rmd
vignettes/mediation.Rmd
vignettes/probability_of_direction.Rmd
vignettes/region_of_practical_equivalence.Rmd

Although nobody asked for this, I have made some minor changes (mostly phrasing and emphasis related) to the vignette for Bayes Factors.

minor rewrite of bayes factor vignette

---

_pkgdown.yml
vignettes/guidelines.Rmd
vignettes/indicesEstimationComparison.Rmd
vignettes/indicesExistenceComparison.Rmd

Not asking for a review, since these are not as substantial as the past edits. Mostly smoothing awkward sentences and styling.

more edits to vignettes

---

DESCRIPTION
R/check_prior.R
R/contr.orthonorm.R
R/describe_posterior.R
R/describe_prior.R
R/diagnostic_draws.R
R/eti.R
R/p_direction.R
R/point_estimate.R
R/print_html.R
R/print_md.R
R/reshape_iterations.R
R/rope_range.R
R/unupdate.R
inst/WORDLIST
man/bic_to_bf.Rd
man/contr.orthonorm.Rd
man/describe_posterior.Rd
man/rope_range.Rd
tests/spelling.R
tests/testthat/test-blavaan.R
tests/testthat/test-check_prior.R
tests/testthat/test-describe_prior.R
tests/testthat/test-p_significance.R
tests/testthat/test-si.R

plus minor styling and spell check

closes #418

---

NEWS.md
R/bayesfactor_inclusion.R
R/bayesfactor_models.R
R/bayesfactor_parameters.R
R/bayesfactor_restricted.R
R/bic_to_bf.R
R/format.R
R/print.R
R/print.bayesfactor_models.R
R/utils_bayesfactor.R
man/bayesfactor_inclusion.Rd
man/bayesfactor_models.Rd
man/bayesfactor_parameters.Rd
man/bayesfactor_restricted.Rd
man/bic_to_bf.Rd
tests/testthat/test-bayesfactor_models.R
tests/testthat/test-bayesfactor_parameters.R
tests/testthat/test-bayesfactor_restricted.R

Refractor Bayes factors

---

NEWS.md
R/describe_posterior.R

Fix log bf in bfbf

---

DESCRIPTION
R/bayesfactor_parameters.R
R/bayesfactor_restricted.R
R/describe_posterior.R
R/equivalence_test.R
R/format.R
R/mediation.R
R/rope.R
R/si.R
R/utils.R
R/utils_hdi_ci.R
R/utils_print_data_frame.R

- removes internal copies
- styling changes

use datawizard helpers

---

NEWS.md
R/distribution.R
R/si.R
man/distribution.Rd
tests/testthat/test-ci.R
tests/testthat/test-distributions.R
tests/testthat/test-hdi.R
tests/testthat/test-rope.R
tests/testthat/test-si.R

Close #508
This is gonna break some stuff....

Use `ppoints()` in `dist_*` functions 

---

DESCRIPTION
R/bayesfactor_models.R
R/bayesfactor_parameters.R
R/bci.R
R/describe_posterior.R
R/equivalence_test.R
R/estimate_density.R
R/eti.R
R/format.R
R/hdi.R
R/p_direction.R
R/p_map.R
R/p_rope.R
R/p_significance.R
R/point_estimate.R
R/print.bayesfactor_models.R
R/rope.R
R/si.R
R/utils.R
R/utils_bayesfactor.R
R/weighted_posteriors.R
tests/testthat/test-describe_posterior.R
tests/testthat/test-emmGrid.R
tests/testthat/test-hdi.R

https://github.com/easystats/easystats/issues/220
style

use insight helpers

---

DESCRIPTION
README.Rmd
vignettes/bayestestR.Rmd
vignettes/credible_interval.Rmd
vignettes/example1.Rmd
vignettes/example2.Rmd
vignettes/web_only/indicesEstimationComparison.Rmd

I let `dplyr` only in the folder "paper". Close #506, close #507

replace tidyr & dplyr by poorman & datawizard

---

vignettes/guidelines.Rmd

This PR fixes a grammatical mistake.
I added a missing closing parentheses in the example of how to report the equivalence test values.

Add a missing ")" on line 137 that opens on line 135

---

DESCRIPTION
README.Rmd
vignettes/example2.Rmd
vignettes/probability_of_direction.Rmd
vignettes/web_only/indicesEstimationComparison.Rmd

https://github.com/easystats/easystats/issues/237#issuecomment-1155233793

Remove poorman from Suggests

---

.github/workflows/R-CMD-check.yaml

https://github.com/easystats/easystats/issues/269

GHA: use Ubuntu latest

---

.github/workflows/R-CMD-check.yaml

https://github.com/easystats/easystats/issues/268

GHA: use new HTML5 check

---

DESCRIPTION
NEWS.md
R/contr.equalprior.R
R/describe_posterior.R
R/estimate_density.R
R/utils.R
R/utils_bayesfactor.R
tests/testthat/test-contr.R

Bump minimum needed R version to `3.6`

---

R/estimate_density.R
R/si.R
R/spi.R
man/estimate_density.Rd
man/si.Rd
man/spi.Rd
tests/testthat/test-si.R

https://github.com/easystats/easystats/issues/317

Fix R CMD check with noSuggests

---

R/utils.R
R/utils_bayesfactor.R
R/utils_check_collinearity.R
R/utils_posterior.R
R/utils_print_data_frame.R
R/weighted_posteriors.R

lintr, code clean-up

---

R/bayesfactor_models.R
R/bci.R
R/bic_to_bf.R
R/check_prior.R
R/diagnostic_draws.R
R/estimate_density.R
R/sexit.R
R/spi.R
R/utils_bayesfactor.R
R/utils_check_collinearity.R
R/utils_hdi_ci.R
R/utils_print_data_frame.R
R/weighted_posteriors.R
man/bic_to_bf.Rd
man/density_at.Rd
man/diagnostic_draws.Rd
man/estimate_density.Rd
man/map_estimate.Rd
man/overlap.Rd
man/p_map.Rd
tests/testthat/test-weighted_posteriors.R
vignettes/bayes_factors.Rmd
vignettes/credible_interval.Rmd
vignettes/example1.Rmd
vignettes/example2.Rmd
vignettes/probability_of_direction.Rmd
vignettes/region_of_practical_equivalence.Rmd

Housekeeping (fix GH action warnings, lintr, code-style, ...)

---

R/equivalence_test.R
man/equivalence_test.Rd

fix examples eq test

---

R/equivalence_test.R
man/equivalence_test.Rd

Fix examples

---

DESCRIPTION

Test on latest datawizard

---

DESCRIPTION
R/utils.R
tests/testthat/test-marginaleffects.R

Use `marginaleffects::get_draws()`

---

DESCRIPTION
NEWS.md
R/describe_posterior.R
inst/WORDLIST
tests/testthat/test-describe_posterior.R

Missing `Response` column for categorical models for {marginaleffects} objects

---

DESCRIPTION
NEWS.md

Prepare CRAN release
